import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import { Container, Galery, Item } from 'components';
import { useElementOnScreen } from 'hooks/useElementOnScreen';
import { sections } from '../src/constants';

const interceptorOpts = {
  root: null,
  rootMargin: '500px',
  threshold: 1.0,
};

const Home: NextPage = () => {
  const itemsObservers = [
    useElementOnScreen(interceptorOpts),
    useElementOnScreen(interceptorOpts),
    useElementOnScreen(interceptorOpts),
    useElementOnScreen(interceptorOpts),
  ];

  const visibleArray = itemsObservers.map((e) => e.isVisible);
  const currentStep = visibleArray.lastIndexOf(true);

  return (
    <div>
      <Head>
        <title>Strapi Animation POC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Galery activeStep={currentStep} />
        {sections.map((section, index) => (
          <Item
            number={index + 1}
            {...section}
            key={section.text}
            itemRef={itemsObservers[index].ref}
          />
        ))}
      </Container>
    </div>
  );
};

export default Home;
