import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from 'next/image';
import { Container, Item } from 'components';
import { sections } from '../src/constants';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Strapi Animation POC</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Container>
      {sections.map((section, index) => (
        <Item number={index + 1} {...section} key={section.text} />
      ))}
    </Container>
  </div>
);

export default Home;
